import type { Metadata } from "next";
import { Roboto,Inter, Source_Code_Pro } from "next/font/google"; // Import Google Fonts
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap", // Improves performance by reducing blocking render time
});

const sourceCodePro = Source_Code_Pro({
  subsets: ["latin"],
  variable: "--font-source-code-pro",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${inter.variable} ${sourceCodePro.variable} antialiased`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
